import sys, os, subprocess, re
from glob import glob
import script_codegen_utils


codegen_cpp_header_comment = '// This file is generated by SpaRcle Studio code-generator ^_^\n\n'

DEFAULT_CPP_TRIVIAL_TYPES = [
    'void', 'bool', 'char', 'int8_t', 'uint8_t', 'int16_t', 'uint16_t', 'float_t', 'bool_t',
    'int32_t', 'uint32_t', 'int64_t', 'uint64_t', 'float', 'double', 'long double', 'int', 'unsigned int',
    'size_t', 'long', 'unsigned long', 'short', 'unsigned short', 'wchar_t', 'char16_t', 'char32_t',
]


def normalize_path(path):
    """Нормализует слеши в путях для различных ОС."""
    return os.path.normpath(path)

def make_serialize_property_name(name):
    if name.startswith('m_'):
        name = name[2:]
    if name.startswith('_'):
        name = name[1:]
    return name


# display name for UI
# example: m_isSomeProperty -> Is Some Property
# example: isSomeProperty -> Is Some Property
# example: is_some_property -> Is Some Property
def make_display_name(name):
    name = make_serialize_property_name(name)
    # 1. Замена snake_case на пробелы и приведение к правильному регистру
    name = re.sub(r'_+', ' ', name)
    # 2. Разделение camelCase и PascalCase на слова
    name = re.sub(r'([a-z])([A-Z])', r'\1 \2', name)
    # 3. Приведение первой буквы каждого слова к верхнему регистру
    name = ' '.join(word.capitalize() for word in name.split())
    return name

def replace_type_templated_name(source: str, templated_type: str, full_type: str) -> str:
    # example:
    # full_type = FullType
    # templated_type = T
    # case 1: source = const T& other -> const FullType& other
    # case 2: source = const std::vector<T>& other) -> const std::vector<FullType>& other
    # case 3: source = const std::vector<T, Allocator>& other) -> const std::vector<FullType, Allocator>& other
    # case 4: source = const std::map<T, T> -> const std::map<FullType, FullType>
    # case 5: source = TypeT<T> -> TypeT<FullType>
    def replace_t_inside_templates(match):
        inside = match.group(1)
        replaced_inside = re.sub(rf'(?<!\w){templated_type}(?!\w)', full_type, inside)  # Заменяем только полные "templated_type
        return f'<{replaced_inside}>'

    # Обрабатываем шаблонные параметры внутри <>
    result = re.sub(r'<([^<>]*)>', replace_t_inside_templates, source)

    # Заменяем оставшиеся одиночные templated_type вне шаблонных параметров
    result = re.sub(rf'(?<!\w){templated_type}(?!\w)', full_type, result)

    return result


def is_trivial_type(type_name: str) -> bool:
    non_qualified_type = remove_type_qualifiers(type_name)
    return non_qualified_type in DEFAULT_CPP_TRIVIAL_TYPES


def remove_type_qualifiers(type_name: str) -> str:
    """Removes qualifiers from a type name."""
    if type_name.startswith('const '):
        type_name = type_name[6:]

    # Удаляем указатели и ссылки
    while type_name.endswith('*') or type_name.endswith('&'):
        type_name = type_name[:-1].strip()

    return type_name


def correct_return_type(return_type: str, code_structure):
    is_return_type_trivial = is_trivial_type(return_type)
    return_type = code_structure.correct_class_name(return_type if is_return_type_trivial else script_codegen_utils.SCRIPT_HANDLE_TYPE_NAME)
    return is_return_type_trivial, return_type