//
// Created by Monika on 27.04.2025.
//

#ifndef SR_ENGINE_SCRIPTING_MACROS_H
#define SR_ENGINE_SCRIPTING_MACROS_H

#include <Utils/macros.h>

#ifdef SR_SCRIPTING_DLL_EXPORTS
    #define SR_SCRIPTING_DLL_API SR_DLL_API_EXPORT
#else
    #define SR_SCRIPTING_DLL_API SR_DLL_API_IMPORT
#endif

#define SR_CODEGEN_DLL_API_EXPORT_SCRIPTING_MODULE SR_CODEGEN_DLL_API_EXPORT
#define SR_CODEGEN_DLL_API_IMPORT_SCRIPTING_MODULE SR_CODEGEN_DLL_API_IMPORT

#endif //SR_ENGINE_SCRIPTING_MACROS_H
