//
// Created by Nikita on 29.12.2020.
// Looked by Drakeme on 26.06.2022.
// Changed by Monika on 20.11.2022
// Approved and improved by innerviewer on 2023-03-09.
// This project was generated by SpaRcle Studio AI on 2025.05.12. ^_^
//

#ifdef SR_ENGINE_STATIC_LIBRARY
    #include <Engine/EntryPoint.h>
#else
    #include "DesktopUtils.h"
    #include "PackUtils.h"
    #include "UnpackUtils.h"
    #include "UnpackedRunner.h"
    #include "OnlineDownloader.h"
#endif

int main(int argc, char** argv) {
#if defined(SR_ENGINE_STATIC_LIBRARY)
    return SREngineEntryPoint(argc, argv);
#else
    const std::string executablePath = argv[0];
    bool allowToUnpack = true;

    for (int i = 1; i < argc; ++i) {
        std::cout << "Command line argument: " << argv[i] << std::endl;
    }

    for (int i = 1; i < argc; ++i) {
        if (strcmp(argv[i], "--pack") == 0) {
            return PackFiles(executablePath, GetPackFiles(executablePath), {}, false);
        }
        if (strcmp(argv[i], "--unpack") == 0) {
            return TryUnpackFiles(executablePath);
        }
        if (strcmp(argv[i], "--pack-with-res") == 0) {
            return PackFiles(executablePath, GetPackFiles(executablePath), GetResourcesPackFiles(), false);
        }
        if (strcmp(argv[i], "--pack-online-data") == 0) {
            return PackFiles(executablePath, GetPackFiles(executablePath), GetResourcesPackFiles(), true);
        }
        if (strcmp(argv[i], "--delete-packed") == 0) {
            allowToUnpack = false;
            DeletePackedFile(argv[i + 1]);
        }
    }

    if (!allowToUnpack) {
        return SREngineEntryPointFromExternalModule(argc, argv, true);
    }

    const int unpackResult = TryUnpackFiles(executablePath);
    if (unpackResult == UNPACK_SUCCESS) {
        return RunUnpackedApplication(executablePath);
    }

    if (unpackResult == UNPACK_NO_PACKED_DATA) {
        const int runResult = SREngineEntryPointFromExternalModule(argc, argv, false);
        if (runResult == 0) {
            return 0;
        }

        if (runResult == ERROR_MODULE_NOT_FOUND) {
            if (int downloadResult = DownloadEngineDataFromGithub(executablePath); downloadResult != 0) {
                std::cerr << "Failed to download engine data from GitHub!" << std::endl;
                return downloadResult;
            }
        }

        if (runResult != ERROR_ENGINE_EXIT) {
            return RunUnpackedApplication(executablePath);
        }
        return runResult;
    }

    return unpackResult;
#endif
}
