//
// Created by Nikita on 29.12.2020.
// Looked by Drakeme on 26.06.2022.
// Changed by Monika on 20.11.2022
// Approved and improved by innerviewer on 2023-03-09.
// This project was generated by SpaRcle Studio AI on 2025.05.12. ^_^
//

#ifdef SR_ENGINE_STATIC_LIBRARY
    #include <Engine/EntryPoint.h>
#else
    #include "DesktopUtils.h"
    #include "PackUtils.h"
    #include "UnpackUtils.h"
    #include "UnpackedRunner.h"
#endif

int main(int argc, char** argv) {
#if defined(SR_ENGINE_STATIC_LIBRARY)
    return SREngineEntryPoint(argc, argv);
#else
    const std::string executablePath = argv[0];
    for (int i = 1; i < argc; ++i) {
        if (strcmp(argv[i], "--pack") == 0) {
            return PackFiles(executablePath, GetPackFiles(executablePath), {});
        }
        if (strcmp(argv[i], "--pack-with-res") == 0) {
            return PackFiles(executablePath, GetPackFiles(executablePath), GetResourcesPackFiles());
        }
        if (strcmp(argv[i], "--delete-packed") == 0) {
            DeletePackedFile(argv[i + 1]);
        }
    }

    const int unpackResult = TryUnpackFiles(executablePath);
    if (unpackResult == UNPACK_SUCCESS) {
        return RunUnpackedApplication(executablePath);
    }

    if (unpackResult == UNPACK_NO_PACKED_DATA) {
        return SREngineEntryPointFromExternalModule(argc, argv);
    }

    return unpackResult;
#endif
}
