//
// Created by Nikita on 29.12.2020.
// Looked by Drakeme on 26.06.2022.
// Changed by Monika on 20.11.2022
// Approved and improved by innerviewer on 2023-03-09.
// This project was generated by SpaRcle Studio AI on 2025.05.12. ^_^
//

#ifdef SR_ENGINE_STATIC_LIBRARY
    #include <Engine/EntryPoint.h>
#else
    #include "DesktopUtils.h"
#endif

int main(int argc, char** argv) {
#ifdef SR_ENGINE_STATIC_LIBRARY
    return SREngineEntryPoint(argc, argv);
#else
    void* pModuleHandle = nullptr;
    namespace fs = std::filesystem;

    for (const auto& entry : fs::directory_iterator(fs::current_path())) {
        if (!entry.is_regular_file() || entry.path().extension() != DYNAMIC_MODULE_EXTENSION) {
            continue;
        }

        if (entry.path().filename().string().find("Engine") != std::string::npos) {
            pModuleHandle = LoadDynamicModule(entry.path().string().c_str());
            if (!pModuleHandle) {
                std::cerr << "Failed to load engine library: " << entry.path() << std::endl;
                return ERROR_MODULE_LOAD_FAILED;
            }
        }
    }

    if (!pModuleHandle) {
        std::cerr << "Engine library not found!" << std::endl;
        return ERROR_MODULE_NOT_FOUND;
    }

    auto&& pEntryPointFunction = FindEngineEntryPoint(pModuleHandle);
    if (!pEntryPointFunction) {
        std::cerr << "Failed to find entry point in Engine library!" << std::endl;
        return ERROR_MODULE_ENTRY_POINT_NOT_FOUND;
    }

    const int code = pEntryPointFunction(argc, argv);
    if (code != 0) {
        std::cerr << "Engine entry point failed with code: " << code << std::endl;
    }

    if (!UnloadDynamicModule(pModuleHandle)) {
        std::cerr << "Failed to unload engine library!" << std::endl;
        return ERROR_MODULE_UNLOAD_FAILED;
    }

    return code != 0 ? code : SUCCESS;
#endif
}
