echo off

set SOURCE_RESOURCES_FOLDER="../Resources"
set DESTINATION_RESOURCES_FOLDER="app/src/main/assets"

del /s /q %DESTINATION_RESOURCES_FOLDER%

echo D|xcopy /s %SOURCE_RESOURCES_FOLDER%/Engine %DESTINATION_RESOURCES_FOLDER%
echo D|xcopy /s %SOURCE_RESOURCES_FOLDER%/Editor %DESTINATION_RESOURCES_FOLDER%
echo D|xcopy /s %SOURCE_RESOURCES_FOLDER%/Libraries %DESTINATION_RESOURCES_FOLDER%
echo D|xcopy /s %SOURCE_RESOURCES_FOLDER%/Launcher %DESTINATION_RESOURCES_FOLDER%


