[All]
Cache/Models
Cache/Scenes
Cache/Shaders
Cache/Textures
Cache/Scripts
Tests
Launcher
Samples/FruitBasketFullJingle.wav
Samples/YuriKozukata
Samples/Well
Samples/Raptoid
Samples/Tsumugi
Samples/MikuHinasaki
Samples/ProceduralWorld
Samples/Grass
Samples/Liza
Samples/Hitler
Samples/Garage
Samples/Cars
Samples/ArmyBox
Engine/Skyboxes/Sea-512x512
Engine/Skyboxes/Sea
Engine/Skyboxes/Room
Engine/Utilities/Tracy.exe
.idea
Engine/SREngine.obj
Engine/SREngine.dll
Engine/SREngine.dylib
Engine/SREngine.so
Samples/Samples.obj
Samples/Samples.dll
Samples/Samples.dylib
Samples/Samples.so
*.pdb
*.git
CMakeLists.txt

[Emscripten]
Engine/Utilities
Samples
Packed
API

[Windows]
Engine/Utilities/glslc
Engine/Utilities/git2

[Linux]
Engine/Utilities/glslc.exe
Engine/Utilities/git2.exe
Engine/Utilities/vs_BuildTools.exe
Engine/Utilities/vswhere.exe