sra format
use tabs: true
0-r:Root
	1-o:asset
		2-v:type
			3-s:FluxGraphAsset
		2-o:ptr
			3-o:graph
				4-a:nodes
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:207599
								8-v:y
									9-f:813.021
							7-v:callableObject
								8-s:GameObject
							7-v:callableFunction
								8-s:GetTransform
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:207324
								8-v:y
									9-f:813.021
							7-v:callableObject
								8-s:FluxComponent
							7-v:callableFunction
								8-s:GetGameObject
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:207486
								8-v:y
									9-f:1076
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0
					5-k:i
						6-o:d
							7-v:type
								8-s:Event
							7-v:name
								8-s:FixedUpdate
							7-o:position
								8-v:x
									9-f:207598
								8-v:y
									9-f:698
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:207550
								8-v:y
									9-f:948
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0.1
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:208143
								8-v:y
									9-f:783.021
							7-v:callableObject
								8-s:Transform
							7-v:callableFunction
								8-s:RotateXYZ
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:207042
								8-v:y
									9-f:813.021
							7-v:callableObject
								8-s:FluxUtils
							7-v:callableFunction
								8-s:GetActiveFluxComponent
				4-a:links
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:6
							7-v:targetNode
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:1
					5-k:i
						6-o:d
							7-v:targetNode
								8-i:5
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:2
							7-v:targetNode
								8-i:5
							7-v:targetPin
								8-i:4
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:2
							7-v:targetNode
								8-i:5
							7-v:targetPin
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:4
							7-v:targetNode
								8-i:5
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:3
							7-v:targetNode
								8-i:5
				4-a:variables
