sra format
use tabs: true
0-r:Root
	1-o:asset
		2-v:type
			3-s:FluxGraphAsset
		2-o:ptr
			3-o:graph
				4-a:nodes
					5-k:i
						6-o:d
							7-v:type
								8-s:Event
							7-v:name
								8-s:FixedUpdate
							7-o:position
								8-v:x
									9-f:191728
								8-v:y
									9-f:1492
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:191279
								8-v:y
									9-f:1876
							7-v:callableObject
								8-s:FluxUtils
							7-v:callableFunction
								8-s:GetActiveFluxComponent
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:191561
								8-v:y
									9-f:1876
							7-v:callableObject
								8-s:FluxComponent
							7-v:callableFunction
								8-s:GetGameObject
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:191836
								8-v:y
									9-f:1876
							7-v:callableObject
								8-s:GameObject
							7-v:callableFunction
								8-s:GetTransform
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:192380
								8-v:y
									9-f:1846
							7-v:callableObject
								8-s:Transform
							7-v:callableFunction
								8-s:RotateXYZ
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:191022
								8-v:y
									9-f:2356
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0.7
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:191022
								8-v:y
									9-f:2484
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:1.1
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:191294
								8-v:y
									9-f:2260
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:191294
								8-v:y
									9-f:2458
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:191292
								8-v:y
									9-f:2644
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:191020
								8-v:y
									9-f:2670
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0.9
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:191534
								8-v:y
									9-f:2260
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:Sin
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:191538
								8-v:y
									9-f:2458
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:Sin
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:191534
								8-v:y
									9-f:2644
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:Cos
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:191394
								8-v:y
									9-f:1720
							7-v:callableObject
								8-s:Time
							7-v:callableFunction
								8-s:DeltaTime
					5-k:i
						6-o:d
							7-v:type
								8-s:WriteVariable
							7-v:name
								8-s:Time
							7-o:position
								8-v:x
									9-f:191998
								8-v:y
									9-f:1492
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:191776
								8-v:y
									9-f:1636
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:SumFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:ReadVariable
							7-v:name
								8-s:Time
							7-o:position
								8-v:x
									9-f:191392
								8-v:y
									9-f:1630
					5-k:i
						6-o:d
							7-v:type
								8-s:ReadVariable
							7-v:name
								8-s:Time
							7-o:position
								8-v:x
									9-f:190734
								8-v:y
									9-f:2260
				4-a:links
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:1
							7-v:targetNode
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:2
							7-v:targetNode
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:3
							7-v:targetNode
								8-i:4
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:5
							7-v:targetNode
								8-i:7
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:6
							7-v:targetNode
								8-i:8
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:10
							7-v:targetNode
								8-i:9
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:7
							7-v:targetNode
								8-i:11
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:8
							7-v:targetNode
								8-i:12
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:9
							7-v:targetNode
								8-i:13
					5-k:i
						6-o:d
							7-v:targetNode
								8-i:15
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:14
							7-v:targetNode
								8-i:16
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:17
							7-v:targetNode
								8-i:16
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:16
							7-v:targetNode
								8-i:15
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:15
							7-v:targetNode
								8-i:4
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:18
							7-v:targetNode
								8-i:7
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:18
							7-v:targetNode
								8-i:8
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:18
							7-v:targetNode
								8-i:9
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:11
							7-v:targetNode
								8-i:4
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:12
							7-v:targetNode
								8-i:4
							7-v:targetPin
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:13
							7-v:targetNode
								8-i:4
							7-v:targetPin
								8-i:4
				4-a:variables
					5-k:item
						6-v:first
							7-s:Time
						6-o:second
							7-v:typeInfo
								8-s:Arithmetic.float
							7-v:float
								8-f:0
