#ifndef SR_ENGINE_PHYSICS_MACROS_H
#define SR_ENGINE_PHYSICS_MACROS_H

#ifndef SR_USE_PCH
    #include <Utils/macros.h>
#endif

#ifdef SR_PHYSICS_DLL_EXPORTS
    #define SR_PHYSICS_DLL_API SR_DLL_API_EXPORT
#else
    #define SR_PHYSICS_DLL_API SR_DLL_API_IMPORT
#endif

#define SR_CODEGEN_DLL_API_EXPORT_PHYSICS_MODULE SR_CODEGEN_DLL_API_EXPORT
#define SR_CODEGEN_DLL_API_IMPORT_PHYSICS_MODULE SR_CODEGEN_DLL_API_IMPORT

#endif //SR_ENGINE_PHYSICS_MACROS_H
