#ifndef SR_ENGINE_IMMEDIATE_GUI_MACROS_H
#define SR_ENGINE_IMMEDIATE_GUI_MACROS_H

#ifndef SR_USE_PCH
    #include <Utils/macros.h>
#endif

#ifdef SR_IMMEDIATE_GUI_DLL_EXPORTS
    #define SR_IMMEDIATE_GUI_DLL_API SR_DLL_API_EXPORT
#else
    #define SR_IMMEDIATE_GUI_DLL_API SR_DLL_API_IMPORT
#endif

#if 0 // enable if needed
    #define SR_RENDER_VALIDATION
#endif

#define SR_CODEGEN_DLL_API_EXPORT_IMMEDIATE_GUI_MODULE SR_CODEGEN_DLL_API_EXPORT
#define SR_CODEGEN_DLL_API_IMPORT_IMMEDIATE_GUI_MODULE SR_CODEGEN_DLL_API_IMPORT

#endif //SR_ENGINE_IMMEDIATE_GUI_MACROS_H
