function(find_windows_sdk SR_WINDOWS_SDK_DIR)
    cmake_host_system_information(RESULT sdk_path QUERY WINDOWS_REGISTRY "HKEY_LOCAL_MACHINE\\SOFTWARE\\WOW6432Node\\Microsoft\\Microsoft SDKs\\Windows\\v10.0" VALUE "InstallationFolder")
    cmake_path(CONVERT ${sdk_path} TO_CMAKE_PATH_LIST sdk_path)
    if(EXISTS ${sdk_path})
        set(${SR_WINDOWS_SDK_DIR} ${sdk_path} PARENT_SCOPE)
        return()
    endif()
    message(WARNING "Windows SDK path wasn't found in the registry. Searching on drives.")
    foreach(drive ${CMAKE_SYSTEM_NAME}:/ C D E F G H I J K L M N O P Q R S T U V W X Y Z)
        set(sdk_path "${drive}:/Program Files (x86)/Windows Kits/10")
        if(EXISTS ${sdk_path})
            set(${SR_WINDOWS_SDK_DIR} ${sdk_path} PARENT_SCOPE)
            return()
        endif()
    endforeach()
    message(FATAL_ERROR "Windows SDK wasn't found on any drive!")
endfunction()

function(find_latest_windows_sdk_version SR_WINDOWS_SDK_VERSION)
    file(GLOB SDK_VERSIONS LIST_DIRECTORIES true "${SR_WINDOWS_SDK_DIR}/Include/*")
    foreach (version ${SDK_VERSIONS})
        message(STATUS "SpaRcle Engine: Found Windows SDK version: ${version}")
    endforeach()

    list(SORT SDK_VERSIONS)
    list(GET SDK_VERSIONS -1 LATEST_SDK_DIR)

    if (LATEST_SDK_DIR)
        string(REGEX MATCH "[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+" LATEST_SDK_VERSION ${LATEST_SDK_DIR})
        set(${SR_WINDOWS_SDK_VERSION} ${LATEST_SDK_VERSION} PARENT_SCOPE)
    else()
        message(FATAL_ERROR "No valid Windows SDK versions found!")
    endif()
endfunction()