name: SpaRcle Engine Linux CI

on:
  workflow_call:

jobs:
  Build:
    name: Build.
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        buildType: [Debug, Release]
        compiler: [gcc, clang]
    steps:
      - name: Fetching repository.
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Installing dependencies.
        run: |
          echo "Used dependencies=$DEPENDENCIES" >> "$GITHUB_ENV"

          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list

          sudo apt update

          # Разделяем строку на отдельные пакеты по пробелам
          IFS=' ' read -r -a DEP_ARRAY <<< "$DEPENDENCIES"

          # Логируем установку каждого пакета
          for DEP in "${DEP_ARRAY[@]}"; do
            echo "[LOG] Installing package $DEP..."
            sudo apt-get install -y $DEP || { echo "Error installing $DEP"; exit 1; }
          done

          # Проверка на успех после установки
          echo "All ubuntu dependencies installed successfully."

          # sudo add-apt-repository universe
          # sudo apt update -y
          # sudo apt upgrade -y
          # sudo apt-get install -y $DEPENDENCIES

          # sudo pip install numpy
          # sudo pip install clang
        env:
          DEPENDENCIES: ${{ vars.UBUNTU_DEPENDENCIES }}

      - name: Install LLVM and libc++
        run: |
          sudo apt update
          sudo apt install -y wget gnupg lsb-release
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17 all
          sudo apt install -y libc++-17-dev libc++abi-17-dev

      - name: Updating submodules.
        run: git submodule --quiet update --init --recursive --depth 1 --jobs 4

      #- name: Installing Ninja.
      #  uses: ashutoshvarma/setup-ninja@v1.1
      #  with:
      #    version: '1.10.2'
      #    dest: '${{github.workspace}}/../ninja'

      - name: Creating Building Environment.
        run: |
          cmake -E make_directory ${{github.workspace}}/build

      - name: Set compiler
        run: |
          if [ "${{ matrix.compiler }}" == "gcc" ]; then
            echo "CC=gcc" >> $GITHUB_ENV
            echo "CXX=g++" >> $GITHUB_ENV
          elif [ "${{ matrix.compiler }}" == "clang" ]; then
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          fi

      - name: Building ${{ matrix.buildType }}.
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          echo "buildSuccessful=false" >> "$GITHUB_ENV"
          cmake -G "Ninja" ../ -DCMAKE_BUILD_TYPE=${{ matrix.buildType }}
          cmake --build . -j 4
          echo "buildSuccessful=true" >> "$GITHUB_ENV"

      - name: Creating a ${{ matrix.buildType }} build trace.
        shell: bash
        working-directory: ${{github.workspace}}/CI
        run: python ninjatracing.py ../build/.ninja_log > trace.json

      - name: Uploading a ${{ matrix.buildType }} build trace artifact.
        uses: actions/upload-artifact@v4
        with:
          name: "SREngine ${{ matrix.buildType }} Linux Build Trace Artifact"
          path: "${{github.workspace}}/CI/trace.json"

      - name: Creating ${{ matrix.buildType }} artifact.
        working-directory: ${{github.workspace}}/build/Engine
        shell: bash
        run: |
          mkdir -p SREngineBuild
          find . -maxdepth 1 -name "SREngine_*" -exec cp {} SREngineBuild/ \;
          ls -la SREngineBuild

      - if: env.buildSuccessful == 'true'
        name: Uploading a successful ${{ matrix.buildType }} build artifact.
        uses: actions/upload-artifact@v4
        with:
          name: "Linux ${{ matrix.buildType }} Executable"
          path: "${{github.workspace}}/build/Engine/SREngineBuild"

      #- if: env.buildSuccessful == 'false'
      #  name: Linux ${{ matrix.buildType }} Build Directory Artifact.
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: "Linux ${{ matrix.buildType }} Build Directory Artifact"
      #    path: "${{github.workspace}}/build"
