name: SpaRcle Engine Linux CI

on:
  workflow_call:

jobs:
  Build:
    name: "Build (${{ matrix.buildType }} | ${{ matrix.compiler }} | ${{ matrix.unity == 'ON' && 'Unity' || 'NoUnity' }})"
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        buildType: [Debug, Release]
        compiler: [gcc, clang]
        unity: [OFF]
        include:
          - buildType: Debug
            compiler: gcc
            unity: ON
          - buildType: Debug
            compiler: clang
            extra: ON
    steps:
      - name: Fetching repository.
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Installing dependencies.
        run: |
          echo "Used dependencies=$DEPENDENCIES" >> "$GITHUB_ENV"

          # wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          # sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list

          sudo apt-get update

          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y universe

          sudo apt-get update
          
          echo "===== APT SOURCES ====="
          grep -r ^deb /etc/apt/
          echo "======================="

          echo "Installing build-essential..."
          sudo apt-get install -y build-essential

          # Разделяем строку на отдельные пакеты по пробелам
          IFS=' ' read -r -a DEP_ARRAY <<< "$DEPENDENCIES"

          echo "::group::📦 Package list"
          echo "[LOG] Installing the following packages:"
          for DEP in "${DEP_ARRAY[@]}"; do
              echo "  - $DEP"
          done
          echo "::endgroup::"

          echo "::group::🚀 Installing all packages at once"
          if ! sudo apt-get install -y "${DEP_ARRAY[@]}"; then
              echo "::endgroup::"
              echo "::group::❗ Fallback: Installing individually"
              for DEP in "${DEP_ARRAY[@]}"; do
                  echo "[TRY] Installing $DEP..."
                  if ! sudo apt-get install -y "$DEP"; then
                      echo "[FAIL] Package $DEP failed to install!"
                      echo "::endgroup::"
                      exit 1
                  else
                      echo "[OK] $DEP installed successfully."
                  fi
              done
              echo "::endgroup::"
              echo "[ERROR] Something went wrong, but fallback succeeded?"
              exit 1
          else
              echo "[LOG] All packages installed successfully."
              echo "::endgroup::"
          fi

          echo "All ubuntu dependencies installed successfully."
        env:
          DEPENDENCIES: ${{ vars.UBUNTU_DEPENDENCIES }}

      - name: Install LLVM, libc++ and gcc-13.
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install -y wget gnupg lsb-release
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17 all
          sudo apt install -y libc++-17-dev libc++abi-17-dev

        # sudo apt install -y libc++-17-dev libc++abi-17-dev gcc-13 g++-13
        # sudo update-alternatives --install /usr/bin/clang   clang   /usr/bin/clang-17   100
        # sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-17 100
        # sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
        # sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
        # clang-17 --version
        # clang++-17 --version

      - name: Updating submodules.
        run: git submodule --quiet update --init --recursive --depth 1 --jobs 4

      #- name: Installing Ninja.
      #  uses: ashutoshvarma/setup-ninja@v1.1
      #  with:
      #    version: '1.10.2'
      #    dest: '${{github.workspace}}/../ninja'

      - name: Creating Building Environment.
        run: |
          cmake -E make_directory ${{github.workspace}}/build

      - name: Set compiler
        run: |
          if [ "${{ matrix.compiler }}" == "gcc" ]; then
            echo "CC=gcc" >> $GITHUB_ENV
            echo "CXX=g++" >> $GITHUB_ENV
          elif [ "${{ matrix.compiler }}" == "clang" ]; then
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          fi

      - name: Building ${{ matrix.buildType }} ${{ matrix.compiler }}.
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          echo "buildSuccessful=false" >> "$GITHUB_ENV"
          cmake -G "Ninja" ../ -DCMAKE_BUILD_TYPE=${{ matrix.buildType }} -DSR_COMMON_UNITY_BUILD=${{ matrix.unity }}
          cmake --build . -j $(nproc || sysctl -n hw.ncpu)
          echo "buildSuccessful=true" >> "$GITHUB_ENV"

      - name: Creating a ${{ matrix.buildType }} build trace.
        shell: bash
        working-directory: ${{github.workspace}}/CI
        run: python ninjatracing.py ../build/.ninja_log > trace.json

      - name: Uploading a ${{ matrix.buildType }} build trace artifact.
        uses: actions/upload-artifact@v4
        with:
          name: "SREngine ${{ matrix.buildType }} ${{ matrix.compiler }} ${{ matrix.unity == 'ON' && 'Unity' || 'NoUnity' }} Linux Build Trace Artifact"
          path: "${{github.workspace}}/CI/trace.json"

      - if: env.buildSuccessful == 'true'
        name: Pack executable with resources
        working-directory: ${{ github.workspace }}/build/Bin
        shell: bash
        run: |
          # Ищем один бинарник, начинающийся с SREngine_
          BIN_FILE=$(find . -maxdepth 1 -type f -perm -u+x -name "SREngine_*" | head -n 1)

          if [ -z "$BIN_FILE" ]; then
            echo "Не найден ни один исполняемый файл SREngine_*"
            exit 1
          fi

          echo "Нашёл бинарник: $BIN_FILE"

          # Запускаем
          "$BIN_FILE" --pack-with-res

          # Ожидаемый packed файл: имя + "-packed"
          PACKED_FILE="${BIN_FILE}-packed"

          if [ ! -f "$PACKED_FILE" ]; then
            echo "Файл $PACKED_FILE не появился. Значит packing не сработал."
            exit 1
          fi

          echo "Packed файл создан: $PACKED_FILE"

          mkdir -p PackedBuild
          cp "$PACKED_FILE" PackedBuild/

          ls -la PackedBuild

      - if: env.buildSuccessful == 'true'
        name: Upload packed build
        uses: actions/upload-artifact@v4
        with:
          name: "Linux ${{ matrix.buildType }} ${{ matrix.compiler }} ${{ matrix.unity == 'ON' && 'Unity' || 'NoUnity' }} SpaRcle Engine"
          path: "${{github.workspace}}/build/Bin/PackedBuild"
