name: SpaRcle Engine Main CI

on:
  push:
    paths-ignore:
      - "Documentation/**"
      - "**.md"
    branches:
      - master
      - dev
      - features/*

  pull_request:
    paths-ignore:
      - "Documentation/**"
      - "**.md"
    branches:
      - master
      - dev
      - features/*

permissions:
  contents: read
  actions: read

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Main CI running"

  BuildWindowsJob:
    needs: Main
    uses: ./.github/workflows/WindowsCI.yml

  TestsWindowsJob:
    needs: BuildWindowsJob
    if: always()
    uses: ./.github/workflows/WindowsTestsCI.yml
    with:
      commitMessage: ${{ github.event.head_commit.message }}
    secrets: inherit

  BuildLinuxJob:
    needs: Main
    uses: ./.github/workflows/LinuxCI.yml

  BuildAndroidJob:
    needs: Main
    uses: ./.github/workflows/AndroidCI.yml

  BuildFlatpakJob:
    needs: Main
    uses: ./.github/workflows/FlatpakCI.yml

  PostBuild:
    needs:
      - TestsWindowsJob
      - BuildLinuxJob
      - BuildAndroidJob
      - BuildFlatpakJob
    if: always()
    uses: ./.github/workflows/PostBuild.yml
    with:
      windowsBuildState: ${{ needs.BuildWindowsJob.result }}
      linuxBuildState: ${{ needs.BuildLinuxJob.result }}
      androidBuildState: ${{ needs.BuildAndroidJob.result }}
      flatpakBuildState: ${{ needs.BuildFlatpakJob.result }}
      commitActor: ${{ github.actor }}
      commitSha: ${{ github.sha }}
      commitBranch: ${{ github.ref_name }}
      commitMessage: ${{ github.event.head_commit.message }}
    secrets: inherit
