name: SpaRcle Engine Windows CI

on:
  workflow_call:

jobs:
  Preparing:
    name: Build.
    runs-on: windows-latest
    strategy:
      matrix:
        buildType: [Debug, Release]

    steps:
      - name: Fetching repository.
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Installing Vulkan.
        uses: TWoolhouse/setup-vulkan-sdk@v1.1.0
        with:
          version: 1.3.211.0

      - name: Preparing MSVC.
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Updating submodules.
        run: git submodule --quiet update --init --recursive --depth 1 --jobs 4

      - name: Installing Ninja.
        uses: seanmiddleditch/gha-setup-ninja@master

      #- name: Installing Ninja.
      #  uses: ashutoshvarma/setup-ninja@v1.1
      #  with:
      #    version: '1.10.2'
      #    dest: '${{github.workspace}}/../ninja'

      - name: Creating Building Environment.
        run: |
          cmake -E make_directory ${{github.workspace}}/build

      - name: Building.
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          echo "buildSuccessful=false" >> "$GITHUB_ENV"
          
          cmake -G "Ninja" ../ \
            -DSR_CI_BUILD=ON \
            -DCMAKE_BUILD_TYPE=${{ matrix.buildType }} \
            -DSR_COMMON_UNITY_BUILD="${{ matrix.buildType == 'Release' && 'ON' || 'OFF' }}" \
            "-DCMAKE_MAKE_PROGRAM=${{ github.workspace }}/ninja-build/ninja.exe"
          
          cmake --build . -j $(nproc || sysctl -n hw.ncpu)
          echo "buildSuccessful=true" >> "$GITHUB_ENV"

      - name: Creating a ${{ matrix.buildType }} build trace.
        shell: bash
        working-directory: ${{github.workspace}}/CI
        run: python ninjatracing.py ../build/.ninja_log > trace.json

      - name: Uploading a ${{ matrix.buildType }} build trace artifact.
        uses: actions/upload-artifact@v4
        with:
          name: "SREngine Windows ${{ matrix.buildType }} Build Trace Artifact"
          path: "${{github.workspace}}/CI/trace.json"

      - if: env.buildSuccessful == 'true'
        name: Pack executable with resources
        working-directory: ${{github.workspace}}/build/Bin
        shell: bash
        run: |
          # Ищем один exe, который начинается с SREngine_
          EXE_FILE=$(find . -maxdepth 1 -type f -name "SREngine_*.exe" | head -n 1)
          
          if [ -z "$EXE_FILE" ]; then
            echo "Не найден ни один SREngine_*.exe"
            exit 1
          fi
          
          echo "Нашёл exe: $EXE_FILE"
          
          # Запускаем его с аргументом
          "$EXE_FILE" --pack-with-res
          
          # После выполнения ожидается файл *-packed.exe
          PACKED_FILE="${EXE_FILE%.exe}-packed.exe"
          
          if [ ! -f "$PACKED_FILE" ]; then
            echo "Файл $PACKED_FILE не появился. Значит packing не сработал."
            exit 1
          fi
          
          echo "Packed файл создан: $PACKED_FILE"
          
          # Копируем packed в специальную директорию под артефакт
          mkdir -p PackedBuild
          cp "$PACKED_FILE" PackedBuild/
          
          ls -la PackedBuild

      - if: env.buildSuccessful == 'true'
        name: Upload packed build
        uses: actions/upload-artifact@v4
        with:
          name: "Windows ${{ matrix.buildType }} SpaRcle Engine"
          path: "${{github.workspace}}/build/Bin/PackedBuild"
