on:
  workflow_call:
    inputs:
      commitMessage:
        required: true
        type: string
    secrets:
      CITOKEN:
        required: true

jobs:
  TestsWindows:
    name: Windows Tests.
    runs-on: windows-latest
    steps:
      - run: |
          echo "Commit Message: ${{ inputs.commitMessage }}"
        name: Debug log.